### ISSUE TITLE
Editor onblur

### ISSUE THREAD

**Issue by k15a** [playgroundsio/frontend#14]
Hide
- [x] line highlighting
- [x] matching brackets
- [x] cursor

on editor onblur event.

Files:
- https://github.com/playgroundsio/frontend/blob/master/src/components/Playground/Editor/Panels/CodeEditor.js

Docs:
- https://github.com/securingsincity/react-ace
- https://ace.c9.io/#nav=api

**Comment by daintycode** [comment]
fixed locally
